### ISSUE TITLE
workflows: setup R to be more reliable 

### ISSUE THREAD

**Issue by zkamvar** [carpentries/assessment-archives#2]
At the moment, the setup-r action will attempt to download the latest R from the internet. In fact, we can use the R version that is pre-installed on GitHub actions like is present in sandpaper:

https://github.com/carpentries/sandpaper/blob/592112589ed80fa0a1f4b5460cb8264bec73c3bb/inst/workflows/sandpaper-main.yaml#L37-L41

```yaml
      - name: "Set up R"
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          install-r: false
```

This would help avoid build errors due to timeouts
